### ISSUE TITLE
Test with HTTP POST/GET to darkroom.bgemyth.net.

### ISSUE THREAD

**Issue by 9214** [9214/daruma#3]
[Bgemyth](http://darkroom.bgemyth.net/) is a French fansite that hosts decoder similar to the one we have here. If you could figure out how to use `write/info` with POST and GET methods and send/fetch Internet code / locker code, then we can plug it into our test suit just to be fancy!

**Comment by jy95** [comment]
Quick notification : Bgemyth also has PC [saves](https://www.bgemyth.net/?page=le_jeu/telechargements/telechargements.php) of this game.

**Comment by 9214** [comment]
@jy95 nice, and they have demos too. 

I don't think save files will be of any use though, since I'm more interested in the differences between decoders (their and mine). Say, in my implementation `fCe\w9!iBXJ1ijn&` is invalid (IIRC because of the overflow during encoding, one bit is inevitably lost), but on their site it (correctly) decodes to `J4D3`.
