### ISSUE TITLE
Fancy icon.

### ISSUE THREAD

**Issue by 9214** [9214/daruma#6]
The one we have now was quickly hacked with my PS madskillz. Alpha section's rounded skullhead (as on pallets in a pallet game) with one eye painted over would be really nice to have.

**Comment by geekyi** [comment]
Did you mean 
![skull](https://user-images.githubusercontent.com/16749930/30174821-c1012ff8-9415-11e7-9fa9-c2fd690aac42.png)
[skull.zip](https://github.com/9214/daruma/files/1285449/skull.zip)

**Comment by geekyi** [comment]
![this](https://vignette3.wikia.nocookie.net/theirisnetwork/images/2/21/Alphasectionarticlelogo.jpg/revision/latest?cb=20131026170053)
!!
http://beyondgoodandevil.wikia.com/wiki/Alpha_Section
I can get you a svg replica! 😉

**Comment by 9214** [comment]
@geekyi no, not that one but slightly different version (painted on the yellow "chips"):

![](https://vignette.wikia.nocookie.net/theirisnetwork/images/b/ba/Disk_game.png/revision/latest?cb=20121210073229)

Should be trivial to rip from the game with [this tutorial](http://beyondgoodandevil.wikia.com/wiki/User_blog:ZyLogic/Beyond_Good_%26_Evil_update_-_Ripping_of_textures,_sound_files_and_others.)
