### ISSUE TITLE
Appreciation ticket

### ISSUE THREAD

**Issue by ynazar1** [9214/daruma#7]
Having stumbled onto your story through the internet... It's absolutely whack and awesome to read through the whole step-by-step process. Huge kudos and I imagine it was an amazing learning experience. 

That being said... Darkroom does exist in a form out there and still is functional here: https://darkroom.bgemyth.net/

**Comment by 9214** [comment]
Hey @ynazar1, thank you for your kind words! Yeah, I'm [aware](https://9214.github.io/13#existing-implementations) of that implementation, and used it quite a lot to validate my own code.
